# Generated by Django 5.1.2 on 2024-10-27 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_invite_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='data_stash',
        ),
    ]
