# Generated by Django 5.1.2 on 2024-10-23 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_userprofile_invite_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wrapped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=dict)),
                ('creator1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator1', to='users.userprofile')),
                ('creator2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator2', to='users.userprofile')),
            ],
        ),
    ]
