# Generated by Django 5.1.2 on 2024-10-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_wrapped_creator2'),
        ('users', '0004_userprofile_invite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrapped',
            name='creator2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator2', to='users.userprofile'),
        ),
    ]
