# Generated by Django 5.1.2 on 2024-10-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_wrapped_creator2'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapped',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
