# Generated by Django 5.1.2 on 2024-10-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_wrapped_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrapped',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
