# Generated by Django 5.1.2 on 2024-10-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_wrapped_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrapped',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
