# Generated by Django 5.1.2 on 2024-10-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_wrapped_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapped',
            name='version',
            field=models.CharField(default='pre-sprint2', max_length=20),
            preserve_default=False,
        ),
    ]
