# Generated by Django 5.1.2 on 2024-11-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_commonfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
            ],
        ),
    ]
