# Generated by Django 5.1.2 on 2024-11-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_previewurls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreviewUrls',
            new_name='PreviewUrl',
        ),
    ]
