# Generated by Django 5.1.2 on 2024-11-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_rename_previewurls_previewurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewurl',
            name='artist',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
